package org.usfirst.frc.team2503.joystick.interfaces;

public interface LeftRightForwardBackRotateDoubleThrottleAxisStickTriggerButtonJoystick extends LeftRightForwardBackRotateDoubleThrottleAxisJoystick, StickTriggerButtonJoystick {}