package org.usfirst.frc.team2503.joystick.interfaces;

public interface LeftRightForwardBackRotateSingleThrottleAxisStickTriggerButtonJoystick extends LeftRightForwardBackRotateSingleThrottleAxisJoystick, StickTriggerButtonJoystick {

}
