package org.usfirst.frc.team2503.joystick.interfaces;

public interface LeftRightForwardBackRotateDoubleThrottleAxisJoystick extends LeftRightForwardBackRotateAxisJoystick, DoubleThrottleAxisJoystick {}