package org.usfirst.frc.team2503.joystick.interfaces;

public interface LeftRightForwardBackRotateLeftRightDoubleThrottleStickTriggerJoystick extends LeftRightForwardBackRotateLeftRightDoubleThrottleJoystick, StickTriggerJoystick {}