package org.usfirst.frc.team2503.joystick.interfaces;

public interface LeftRightForwardBackRotateLeftRightDoubleThrottleJoystick extends LeftRightForwardBackRotateJoystick, LeftRightDoubleThrottleJoystick {
}
